<section class="cw-py-5">
	<div class="container">
		<div class="cw-row">
				<div class="cw-col-lg-8">
				<div class="cw-text-block">
					<p>Der Index Theologicus (IxTheo) ist eine internationale wissenschaftliche Open-Access-Bibliographie für Theologie und umfasst konfessions-, sprachen-, zeit- und medienübergreifend wissenschaftliche Ressourcen über die christliche Theologie, deren historische Verflechtungen sowie wissenschaftlichen Dialog mit anderen Religionen. Herausgeber sind die <a href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/">Universitätsbibliothek Tübingen</a>, die <a href="https://uni-tuebingen.de/fakultaeten/evangelisch-theologische-fakultaet/fakultaet/aktuelles/">Evangelisch-Theologische Fakultät Tübingen</a> und die <a href="https://uni-tuebingen.de/fakultaeten/katholisch-theologische-fakultaet/fakultaet/">Katholisch-Theologische Fakultät Tübingen</a>.</p>
					<p>IxTheo ist ein mordernes und facettenbasiertes Discovery-System auf der technischen Basis von <a href="https://vufind.org/vufind/">VuFind</a>. Zur Strukturierung der mehr als 2 Millionen Titel im IxTheo stehen fachliche Einstiege für einzelne Sektionen, Fächer und Spezialsammlungen der Theologie zur Verfügung.</p>
					<p>Seit 2015 wird IxTheo im Rahmen des Fachinformationsdienstes (FID) Theologie mit Förderung der Deutschen Forschungsgemeinschaft (DFG) technisch und inhaltlich weiterentwickelt. Ziel des FID Theologie ist es, die Informationsinfrastruktur an den einzelnen Forschungsstandorten durch die Bereitstellung spezialisierter Medien und weitere Mehrwertdienste zu ergänzen und sich dabei eng an den fachspezifischen Interessen der Forschung zu orientieren.</p> 
					<p>Mehr Informationen über das Förderprogramm "Fachinformationsdienste für die Wissenschaft" finden Sie <a href= "https://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/fachinfodienste_wissenschaft/">hier</a>
					</p>
				</strong>	
			<div id="accordion" role="tablist">
                <div class="cw-card cw-border-0 cw-shadow cw-mb-3">
                <div id="headingOne" role="tab" class="cw-card-header cw-bg-primary-100 cw-border-0 cw-py-0"><a data-toggle="collapse" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" class="cw-accordion-link collapsed" aria-selected="false" tabindex="0">Aufgabenfelder des FID Theologie 2018-2020</a></div>
                <div id="collapseOne" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion" class="collapse" style="height: 0px;" aria-expanded="false" aria-hidden="true" tabindex="-1" aria-selected="false">
                    <div class="cw-card-body cw-py-5">
					<h4>Bibliographie</h4>
					<ul>
						<li>Umfassender, systematischer Nachweis von Monographien</li>
						<li>Einbezug ausgewählter Rezensionsorgane</li>
						<li>Nachweis aller relevanten Datenbanken</li>
						<li>Integration von freien elektronischen Zeitschriften und digitalen Inhalten</li>
						<li>Erweiterung des Spektrums ausgewerteter Zeitschriften auf rund 1.200 Zeitschriften</li>
						<li>Nachweis und Recherche von Nachlässen von Theologinnen und Theologen</li>
					</ul>
					<h4>Verbesserte Features</h4>
					<ul>
						<li>Übertragung des Bibelstellensuche-Algorithmus auf andere gezählte Quellen, z.B. den Canones des Codex Iuris Canonici</li> 
						<li>Verbesserte Alerting-Services: Alerting auf Fachsegemente und / oder individuelle Themen</li> 
					</ul>
					<h4>Volltextsuche</h4>
					<ul>
						<li>Entwicklung einer Volltextsuche für kommerzielle Titel und Open-Access-Titel. Pilotprojekt mit zwei renommierten Fachverlagen, um in einer Open-Access-Umgebung auch kommerzielle Titel verschiedener Verlage gleichzeitig und auf legalem Wege durchsuchen zu können</li>
					</ul>
					<h4>IxTheo Open Journals</h4>
					<ul>
						<li>Bereitsstellung und Support eines Zeitschriften-Publikationssystems OJS</li>
					</ul>
					<h4>IxTheo Open Text</h4>
					<ul>
						<li>Der FID Theologie bietet Wissenschaftlerinnen und Wissenschaftlern im Rahmen der Möglichkeiten des Urheberrechts einen Zweitveröffentlichungsservice an. Dabei übernimmt der FID die Herstellung und die Kosten der Digitalisierung, der Katalogisierung und der Zweitveröffentlichung innerhalb des Fachrepositoriums Theologie</li>
					</ul>  
                    </div>
                </div>
            </div>
            <div class="cw-card cw-border-0 cw-shadow cw-mb-3">
                <div id="headingTwo" role="tab" class="cw-card-header cw-bg-primary-100 cw-border-0 cw-py-0"><a data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" class="cw-accordion-link collapsed" aria-selected="false" tabindex="0">Aufgabenfelder des FID Theologie 2015-2017</a></div>
                <div id="collapseTwo" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion" class="collapse" style="height: 0px;" aria-expanded="false" aria-hidden="true" tabindex="-1" aria-selected="false">
                    <div class="cw-card-body cw-py-5">
                    <h4>Ausbau des IxTheo als forschungsorientiertes Recherchesystem</h4>
					<ul>
					<li> Inhatliche, organisatorische und technische Weiterentwicklung vom IxTheo auf der Basis eines mordernen und frei verfübaren Resource Discovery System </li>	
					</ul>
					<h4>Erwerbung und Sammlung theologischer Literatur</h4>
					<ul>
					<li> Sammelprofil orientiert primär an der Bibliographieerstellung und sekundär an einer Last Resort Funktion
					</ul>
					<h4> Ausbau von Open-Access-Services</h4>
					<ul>
					<li> Fachrepositorium </li>
					<li> IxTheo Open Journals </li>
					</ul>
                    </div>
                </div>
            </div>
			<hr>      
			<strong>Ansprechpartner</strong>
              <p>► <a href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/formulare/kontakt/fassnacht/">Dr. Martin Faßnacht</a> (Leiter)<br>
              ► <a href="https://www.ub.uni-tuebingen.de/formulare/kontakt/Kim.html">Timotheus Chang Whae Kim</a> (Stv. Leiter)<br>
                ► <a href= "https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/formulare/kontakt/aprile/">Dr. Alessandro Aprile</a> (Projektmitarbeiter)</p><hr>
        </div>
