<div class="container cw-py-5">
    <div class="cw-row">
	<div class="cw-col-lg-8">
    <div class="cw-text-block">
	<h1 class="cw-h1">Discover</h1>
	<p>IxTheo enthält mehr als 2 Mio. Titel in zehn verschiedenen Sprachen. Ca. 15.000 neue Titel kommen jährlich hinzu. Um eine präzise und diversifizierte Suche nach den gewünschten Ressourcen innerhalb dieser großen Informationsmenge zu ermöglichen, stehen Ihnen verschiedene Features zur Verfügung:</p>
		<div class="cw-card cw-border-0 cw-shadow cw-mb-3">
                <div id="headingTwo" role="tab" class="cw-card-header cw-bg-primary-100 cw-border-0 cw-py-0"><a data-toggle="collapse" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" class="cw-accordion-link collapsed">Inhaltliche Suche</a></div>
                <div id="collapseOne" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion" class="collapse">
                    <div class="cw-card-body cw-py-5">
					<h4>IxTheo-Klassifikation</h4>
						<p>Unter dem Button "Erweiterte Suche" befindet sich die IxTheo-Klassifikation. Durch das Anklicken können Sie entsprechende Klasse auswählen. Auch mehrere Klassen können als Block durch das Halten der Umstell-Taste beim Anklicken markiert werden. Mehrere einzelne Klassen werden durch das Halten der „Kommando"-Taste (auf Apple Computer) oder der „Strg-Taste" (auf Windows Computer) beim Anklicken markiert</p>
                        <p>Duch den Klick auf "Suche" starten Sie dann eine gezielte Suche nach den ausgewählten IxTheo-Klassen</p>
					<h4>Verbale Suchbegriffe</h4>
						<p>Tippen Sie den Suchbegriff in den Suchschlitz und belassen Sie den Suchaspekt auf „Alle Felder“. Der eingegebene Begriff wird dann in allen Suchfeldern gesucht. Für eine inhaltliche Suche ist die Auswahl des Suchaspektes „Schlagwort“ von großem Nutzen. Hier werden intellektuell vergebene Schlagwörter und Schlagwortfolgen durchsucht</p>
                    </div>
                </div>
            </div>
		<div class="cw-card cw-border-0 cw-shadow cw-mb-3">
                <div id="headingThree" role="tab" class="cw-card-header cw-bg-primary-100 cw-border-0 cw-py-0"><a data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" class="cw-accordion-link collapsed">Bibelstellensuche</a></div>
                <div id="collapseTwo" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion" class="collapse">
                    <div class="cw-card-body cw-py-5">
                        <p>Die Bibelstellensuche wurde völlig neu konzipiert und orientiert sich an den Bedürfnissen eines wissenschaftlichen Nutzers. Um die Bibelstellensuche zu aktivieren muss rechts neben dem Suchschlitz der Suchaspekt „Bibelstellen“ ausgewählt werden.</p>
                        <p>Die Bibelstellen können in der international üblichen Form und mit den bekannten Abkürzungen eingegeben werden. Es sind auch Abkürzungen, wie sie in den Sprachen englisch, französisch, italienisch und spanisch verwendet werden sowie die von Nestle-Aland und der Vulgata genutzten Formen möglich. In wenigen Fällen gab es durch die Benennungen der Bibelbücher in den verschiedenen Sprachen Ambiguitäten bei den Abkürzungen. So wird z.B. die Abkürzung „es“ im Französischen für das Jesajabuch, im Italienischen aber für das Buch Exodus verwendet. In diesen Fällen musste eine Entscheidung getroffen werden, welche Abkürzungen zugelassen werden, damit keine uneindeutigen Treffer erzeugt werden. Die Liste der gültigen Abkürzungen für die Bibelstellensuche finden Sie hier.</p>
						<p>Geben Sie die gesuchte Stelle in folgender Form ein: Abkürzung_des_Bibelbuches Kapitel, Versangaben. <div>Beispiele:</div></p>
						<ul>
						<p>Joh 5,1-20 oder Jn 5,1-20</p>
						<p>1Kor 10 oder 1 Kor 10 oder 1 K 10</p>
						<p>Röm 14,1-15,13 oder Rm 14,1-15,13</p>
						</ul>
						<p>Die Sortierung der Treffer erfolgt nach der Nähe zur gesuchten Stelle:</p>
						<ul>
						<p>Exakter Treffer: die eingegebene Stelle hat eine genaue Übereinstimmung mit der gefundenen Stelle:</p>
						<p>Beispiel: Suche nach Mk 5,25-34 findet Mk 5,25-34</p>
						<p>Enthaltene Treffer: die eingegebene Stelle hat eine Überschneidung mit der gefundenen Stelle</p>
						<p>Beispiel: Suche nach Mk 5,25-34 findet Mk 5,24-34</p>
						<p>Indirekter Treffer: die eingegebene Stelle ist Teil des zugehörigen Kapitels der Bibelstelle</p>
						<p>Beispiel: Suche nach Mk 5,25-34 findet Mk 5<p>
						</ul>
						<p>Es werden aber auch alle Titel gefunden, die verbal mit dem Normsatz „Blutflüssige Frau“ verbunden sind. Diesem Normsatz sind die synoptischen Stellen Mk 5,25-34 sowie Mt 9,20-22 und Lk 8,43-48 zugeordnet.</p>
						<p>Achtung: Da noch nicht alle Titel mit den Normsätzen der Bibelstellen verknüpft sind, lohnt sich auch immer noch eine Suche nach der Bibelstelle mit dem Suchaspekt „Alle Felder“. Die Vorteile der IxTheo-Bibelstellensuche sind dann aber nicht gegeben.</p>
						<p>Bei der technischen Umsetzung des neuen IxTheo-Bibelstellen Suchkonzeptes wird die als verbaler String eingegebene Stelle in eine achtstellige numerische Zahlenfolge übersetzt, mit der im Anschluss gerechnet werden kann. Dabei entsprechen die beiden ersten Zahlen dem Bibelbuch, die folgenden drei Stellen dem Kapitel und die letzten drei Zahlen dem Vers. Mk 5,25-34 wird folgendermaßen umgesetzt: 02005025_02005034. Um die Nähe der gefundenen Stellen zur gesuchten Stelle zu berechnen, wird ein Scoring-Wert gebildet. Weiterführende Informationen finden sich hier</p>
					</div>
                </div>
            </div>
		<div class="cw-card cw-border-0 cw-shadow cw-mb-3">
                <div id="headingTwo" role="tab" class="cw-card-header cw-bg-primary-100 cw-border-0 cw-py-0"><a data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree" class="cw-accordion-link collapsed">Browsen</a></div>
                <div id="collapseThree" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion" class="collapse">
                    <div class="cw-card-body cw-py-5">
					<h4>IxTheo-Themen Browsing</h4>
                     <p>Sie finden den Browsing Modus durch Klick auf „Browsen“ unterhalb des Suchschlitzes.</p>
					 <p>Es öffnet sich ein weiterer Suchschlitz, in den Sie Ihren Suchbegriff eingeben. Er dient als Startpunkt des Browsens.</p>
					 <p>Beispiel 1: geben Sie den Begriff „Gott“ ein. Sie sehen dann eine spezielle Liste mit Schlagwortfolgen, in denen der Begriff Gott vorkommt.</p>
					 <p>Beispiel 2: geben den Begriff „Gott“ und „Bibel“ ein. Sie sehen dann eine spezielle Liste mit Schlagwortfolgen, in denen der Begriff „Gott“ und „Bibel“ vorkommt.</p>
					 <p>Wenn Sie rechts oben auf der Website die Sprache auf Englisch ändern, werden die Begriffe im Englischen angezeigt, wenn sie in der Sprachkonkordanz vorhanden sind.</p>
					 <h4>Katalogbrowsen</h4>
					 <p>Die Standard-Browsing Funktion der Software des IxTheo (VuFind) ermöglicht das Browsen in verschiedenen Feldern: DDC-Klassifikation, IxTheo-Klassifikation, Thema (Schlagwort), Verfasser und Verlag. In einem weiteren Schritt kann hier das Browsing durch andere Felder eingeschränkt werden.</p>
					 <p>Beispiel: Wählen Sie „Verfasser“, dann „Nach IxTheo-Klassifikation“, dann „HB Altes Testament“ aus. Sie sehen dann eine Liste von Autoren, die im Bereich des Alten Testaments publiziert haben, sortiert nach Häufigkeit der Titel im IxTheo.</p>
					 <h4>Alphabetisch browsen</h4>
					 <p>Hier können Sie bestimmen, an welcher Stelle des Alphabets Sie in das Browsing einsteigen wollen. Nach der Auswahl des Browsingaspektes (möglich sind „Thema“, Verfasser, Titel und DDC-Klassifikation) geben Sie den Buchstaben ein, ab dem das Browsing starten soll.</p>
					 <p>Beispiel 1: Wählen Sie „Nach Verfasser“ und geben Sie ein: ab „Z“. Es werden dann alle Verfasser aufgelistet, die mit dem Buchstaben Z beginnen.</p>
					 <p>Beispiel 2: Wählen Sie „Nach Titel“ und geben Sie ein: ab „Tr“. Es werden dann alle Titel aufgelistet, die mit der Buchstabenfolge Tr beginnen.</p>
                    </div>
                </div>
            </div>
		<div class="cw-card cw-border-0 cw-shadow cw-mb-3">
                <div id="headingTwo" role="tab" class="cw-card-header cw-bg-primary-100 cw-border-0 cw-py-0"><a data-toggle="collapse" href="#collapseFour" aria-expanded="false" aria-controls="collapseTwo" class="cw-accordion-link collapsed">Personalisierung</a></div>
                <div id="collapseFour" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion" class="collapse">
                    <div class="cw-card-body cw-py-5">
                     <p>Viele nützliche Funktionen stehen Ihnen zur Verfügung, wenn Sie einen persönlichen Account anlegen. Nach einer einmaligen Registrierung können Sie sich in Ihren Account einloggen. Um sich zu registrieren oder einzuloggen klicken Sie auf den Link „Login“ rechts oben. Durch Klick auf „Ihr Konto“ kommen Sie in Ihren personalisierten Bereich. Dort stehen Ihnen u.a. folgende Funktionen zur Verfügung:</p>
					 <h4>Alerting-Funktion</h4>
					 <p>Die Alerting Funktion unterrichtet Sie über neu erschienene Aufsätze aus Zeitschriften und neu erschienene Bände in Reihen. Sie können frei entscheiden, in welchen Fällen Sie eine Benachrichtigung wünschen. Um eine Zeitschrift oder eine Reihe für das Alerting auszuwählen, müssen Sie die Gesamtaufnahme der Zeitschrift oder Reihe subskribieren. Klicken Sie dazu auf das Symbol "Glocke", die Sie rechts im entsprechenden Datensatz sehen. In Ihrem Konto können Sie die Subskriptionen verwalten.</p>
					 <p>Beispiel 1: Um die Theologische Quartalschrift zu subskribieren, recherchieren Sie nach dem Titel der Reihe oder geben Sie in den Suchschlitz die Abkürzung „ThQ“ ein. Wählen Sie im Anschluss unter Medienart die Facette Zeitschrift aus. Sie haben 2 Treffer: zum einen die Gesamtaufnahme der gedruckten, zum anderen die Gesamtaufnahme der elektronischen Zeitschrift der ThQ. In diesem Fall ist es sinnvoll, beide Medienarten zu subskribieren.</p>
					 <p>Beispiel 2: Um die Reihe „Wissenschaftliche Untersuchungen zum Neuen Testament“ zu subskribieren, recherchieren Sie nach dem Titel der Reihe oder geben Sie in den Suchschlitz die Abkürzung „WUNT“ ein. Sie haben mehrere Treffer. Subskribieren Sie die gewünschte Reihe durch Klick auf das Symbol „Glocke“.</p>
					 <p>Wir werden uns bemühen, die Auswahl der Zeitschriften und Reihen für das Alerting zukünftig bequemer für Sie zu gestalten. Angedacht ist, dass Sie Zeitschriften, die im IxTheo ausgewertet werden, geordnet nach Disziplinen im Block subskribieren können. </p> 
					 <h4>Suchanfragen speichern</h4>
					 <p>Ihre aktuellen Suchanfragen werden in der Suchhistorie temporär gespeichert. Wenn Sie die Suchanfragen dauerhaft verwenden wollen, können Sie sie in Ihrem Konto abspeichern. Sie stehen dann in Ihrem Konto dauerhaft zur Verfügung und können durch Anklicken erneut ausgeführt werden. Das lohnt sich für komplexe Abfragen oder für Themen, an denen Sie kontinuierlich interessiert sind. Auf diese Weise entdecken Sie leicht die neu erschienene Literatur zu einem bestimmten Thema oder Themengebiet.</p>
					 <h4>Favoriten speichern</h4>
					 <p>Speichern Sie interessante Titel direkt in Ihrem Konto ab. Damit stehen Sie Ihnen dauerhaft zur Verfügung und Sie müssen nicht viel Zeit mit dem Wiederfinden verwenden. Damit die Favoriten geordnet werden können, werden Sie in Listen gespeichert, die Sie definieren können. So können interessante Titel gewissen Forschungsprojekten oder Themen zugeordnet werden.</p>
					 <p>Aus Ihrem Konto heraus können Sie Favoriten exportieren, per Mail verschicken oder Ausdrucken.</p>
                    </div>
                </div>
            </div>

				
					
			
			
